#! /bin/bash

# check
if [[ "$STREET" == "" || "$SINGLE_OUT" == "" || "$MULTIPLIER" == "" ]]; then
  echo Run \'. ./setup\'.
  exit
fi

function check
{
    if [ ! -f $1 ]; then
        echo missing "'$1'".
        exit
    fi
}

check $STREET

if [ ! -d $SINGLE_OUT ]; then
    echo missing "'$SINGLE_OUT'".
    exit
fi

leaves=$SINGLE_OUT'z_leaves'
check $leaves

# outputs
leaves_sim=$SINGLE_OUT'z_leaves_sim'

cmd="$STREET -v --sim_leaf --input_leaf $leaves --texture_multiplier $MULTIPLIER -l $leaves_sim $@"
echo $cmd
eval "$cmd"
